const VARS=["a","astar","y","ystar","i","istar","m","mstar","pi","pistar","pil1","in","instar","x","xstar"];
const IDX=Object.fromEntries(VARS.map((v,i)=>[v,i]));
const N=VARS.length;
export const PAPER_PARAMS=Object.freeze({beta:.995,gam:5,vphi:5,sig:1.5,alpha:.75,n:.15507142857142855,xi:.8512857142857143,rho_i:.78,rho_istar:.78,phi_pi:1.33,phi_pistar:1.33,phi_x:1.29,phi_xstar:1.29,iota:0,deltaa:.95,deltaastar:.95,stda:.7,stdastar:.7,corraastar:.25,deltam:0,deltamstar:0,stdm:.38,stdmstar:.38,corrmmstar:.5});
export const PARAM_GROUPS=[
{title:"Structural parameters",help:"Country size, openness, preferences, substitution, and price rigidity.",params:[["n","Home country size, n",.01,.95,.001],["xi","Home-goods share, xi",.01,.999,.001],["beta","Discount factor, beta",.9,.999,.001],["gam","Risk aversion, gamma",.1,20,.1],["vphi","Inverse Frisch elasticity, varphi",.1,20,.1],["sig","Trade elasticity, sigma",.1,10,.05],["alpha","Calvo parameter, alpha",.01,.99,.01]]},
{title:"Monetary policy rule",help:"Taylor-rule inertia and responses. Wicksellian rules also track the natural rate.",params:[["rho_i","Home interest-rate smoothing",0,.99,.01],["rho_istar","Foreign interest-rate smoothing",0,.99,.01],["phi_pi","Home inflation response",0,5,.01],["phi_pistar","Foreign inflation response",0,5,.01],["phi_x","Home slack response",0,5,.01],["phi_xstar","Foreign slack response",0,5,.01],["iota","Natural-rate tracking",0,1,1]]},
{title:"Shock processes",help:"Innovation standard deviations and persistence. Correlations are shown for consistency with the stochastic model.",params:[["deltaa","Home productivity persistence",0,.999,.001],["deltaastar","Foreign productivity persistence",0,.999,.001],["stda","Home productivity std. dev.",.001,5,.001],["stdastar","Foreign productivity std. dev.",.001,5,.001],["corraastar","Productivity innovation correlation",-.99,.99,.01],["deltam","Home monetary persistence",0,.999,.001],["deltamstar","Foreign monetary persistence",0,.999,.001],["stdm","Home monetary std. dev.",.001,5,.001],["stdmstar","Foreign monetary std. dev.",.001,5,.001],["corrmmstar","Monetary innovation correlation",-.99,.99,.01]]}
];
export const SERIES=[
{id:"pi",group:"home",label:"Home inflation",variable:"pi",unit:"percent"},{id:"employment",group:"home",label:"Home employment",variable:"employment",unit:"percent deviation from steady state"},{id:"y",group:"home",label:"Home output",variable:"y",unit:"percent deviation from steady state"},{id:"growth",group:"home",label:"Home output growth",variable:"y",unit:"percent log difference"},{id:"i",group:"home",label:"Home interest rate",variable:"i",unit:"percent"},{id:"in",group:"home",label:"Home natural interest rate",variable:"in",unit:"percent"},{id:"tb",group:"home",label:"Home trade balance",variable:"tb",unit:"percent"},{id:"tot",group:"home",label:"Home terms of trade and real exchange rate",variable:"tot",secondaryVariable:"rs",unit:"percent deviation from steady state",note:"Solid: terms of trade. Dashed: real exchange rate."},
{id:"pistar",group:"foreign",label:"Foreign inflation",variable:"pistar",unit:"percent"},{id:"employmentStar",group:"foreign",label:"Foreign employment",variable:"employmentStar",unit:"percent deviation from steady state"},{id:"ystar",group:"foreign",label:"Foreign output",variable:"ystar",unit:"percent deviation from steady state"},{id:"growthStar",group:"foreign",label:"Foreign output growth",variable:"ystar",unit:"percent log difference"},{id:"istar",group:"foreign",label:"Foreign interest rate",variable:"istar",unit:"percent"},{id:"instar",group:"foreign",label:"Foreign natural interest rate",variable:"instar",unit:"percent"},{id:"tbstar",group:"foreign",label:"Foreign trade balance",variable:"tbstar",unit:"percent"},{id:"totstar",group:"foreign",label:"Foreign terms of trade and real exchange rate",variable:"totstar",secondaryVariable:"rsstar",unit:"percent deviation from steady state",note:"Solid: terms of trade. Dashed: real exchange rate."},
{id:"a",group:"shock",label:"Home productivity shock process",variable:"a",unit:"percent deviation from steady state",shockKind:"productivity"},{id:"astar",group:"shock",label:"Foreign productivity shock process",variable:"astar",unit:"percent deviation from steady state",shockKind:"productivity"},{id:"m",group:"shock",label:"Home monetary shock process",variable:"m",unit:"percent",shockKind:"monetary"},{id:"mstar",group:"shock",label:"Foreign monetary shock process",variable:"mstar",unit:"percent",shockKind:"monetary"}
];
export const cloneParams=p=>JSON.parse(JSON.stringify(p));
export const getXistar=p=>p.n*(1-p.xi)/(1-p.n);
function comp(p){const xs=getXistar(p),eta=p.n*p.xi/(p.n*p.xi+(1-p.n)*xs),etas=p.n*(1-p.xi)/(p.n*(1-p.xi)+(1-p.n)*(1-xs)),D=p.sig-(p.sig-1/p.gam)*(p.xi-xs)*(eta-etas),AH=p.sig*(eta*(1-p.xi)+(1-eta)*(1-xs))-(1-eta)*(p.xi-xs)/p.gam,AF=-p.sig*(etas*p.xi+(1-etas)*xs)-(1-etas)*(p.xi-xs)/p.gam,chi=(p.xi-xs)/p.gam,kappa=(1-p.alpha)*(1-p.beta*p.alpha)/p.alpha,c={xistar:xs,eta,etastar:etas,D,AH,AF,chi,kappa};
c.Psi1=p.xi*p.vphi+p.gam*(p.sig*p.xi-(p.sig-1/p.gam)*(p.xi-xs)*(1-etas))/D;
c.Psi2=(1-p.xi)*p.vphi+p.gam*(p.sig*(1-p.xi)+(p.sig-1/p.gam)*(p.xi-xs)*(1-eta))/D;
c.Psi1star=xs*p.vphi+p.gam*(p.sig*xs+(p.sig-1/p.gam)*(p.xi-xs)*etas-(1-1/p.gam)*xs*(p.xi-xs))/D;
c.Psi2star=(1-xs)*p.vphi+p.gam*(p.sig*(1-xs)-(p.sig-1/p.gam)*(p.xi-xs)*eta+(1-1/p.gam)*xs*(p.xi-xs))/D;
c.ThetaTot=(1+p.vphi)/(1+p.vphi*D);c.OmegaRS=p.xi-xs;c.omegaTB=(1-p.n)*xs;c.OmegaTB=p.sig-1+(p.sig-1/p.gam)*(p.xi-xs);
c.LambdaXi=(AH+chi)/chi;c.LambdaXistar=AH/chi;c.LambdaXstarI=-(AF+chi)/chi;c.LambdaXstarIstar=-AF/chi;
c.LambdaCa=(1+p.vphi)/(p.gam+p.vphi)-((p.vphi*AH+(1-p.xi))/(p.gam+p.vphi))*((1+p.vphi)/(1+p.vphi*D));
c.LambdaCastar=((p.vphi*AH+(1-p.xi))/(p.gam+p.vphi))*((1+p.vphi)/(1+p.vphi*D));
c.LambdaCstara=c.LambdaCa-((p.xi-xs)/p.gam)*c.ThetaTot;c.LambdaCstarastar=c.LambdaCastar+((p.xi-xs)/p.gam)*c.ThetaTot;
c.LambdaYa=c.LambdaCa+AH*c.ThetaTot;c.LambdaYastar=c.LambdaCastar-AH*c.ThetaTot;c.LambdaYstara=c.LambdaCa+AF*c.ThetaTot;c.LambdaYstarastar=c.LambdaCastar-AF*c.ThetaTot;
c.NaturalIa=p.gam*c.LambdaCa*(p.deltaa-1);c.NaturalIastar=p.gam*c.LambdaCastar*(p.deltaastar-1);c.NaturalIstara=p.gam*c.LambdaCstara*(p.deltaa-1);c.NaturalIstarastar=p.gam*c.LambdaCstarastar*(p.deltaastar-1);return c}
export function validateParams(p){const messages=[],warnings=[],xs=getXistar(p);if(!(p.n>0&&p.n<1))messages.push("n must be between 0 and 1.");if(!(p.xi>0&&p.xi<1))messages.push("xi must be between 0 and 1.");if(!Number.isFinite(xs)||xs<0||xs>1)messages.push("The zero-trade-balance restriction implies xi* outside [0, 1].");if(p.xi<p.n)messages.push("Home bias requires xi to be at least as large as n under zero steady-state trade balance.");if(p.xi<=xs)warnings.push("The selected values do not display home bias (xi should exceed xi*).");const c=comp(p);for(const[k,v]of Object.entries(c))if(!Number.isFinite(v))messages.push(`Composite coefficient ${k} is not finite.`);if(Math.abs(c.chi)<1e-8)messages.push("xi is too close to xi*, which makes the current reduced system ill-conditioned.");return{ok:!messages.length,messages,warnings,xistar:xs,composite:c}}
function z(){return Array.from({length:N},()=>Array(N).fill(0))}function add(B,r,n,v){B[r][IDX[n]]+=v}
function blocks(p,c){const L=z(),C=z(),U=z(),io=Number(p.iota||0);add(U,0,"x",p.gam);add(C,0,"x",-p.gam);add(C,0,"i",-c.LambdaXi);add(C,0,"in",c.LambdaXi);add(U,0,"pi",c.LambdaXi);add(C,0,"istar",c.LambdaXistar);add(C,0,"instar",-c.LambdaXistar);add(U,0,"pistar",-c.LambdaXistar);add(C,1,"pi",1);add(U,1,"pi",-p.beta);add(C,1,"x",-c.kappa*c.Psi1);add(C,1,"xstar",-c.kappa*c.Psi2);add(C,2,"i",1);add(L,2,"i",-p.rho_i);add(C,2,"pi",-(1-p.rho_i)*p.phi_pi);add(C,2,"x",-(1-p.rho_i)*p.phi_x);add(C,2,"in",-(1-p.rho_i)*io);add(C,3,"in",1);add(C,3,"a",-c.NaturalIa);add(C,3,"astar",-c.NaturalIastar);add(U,4,"xstar",p.gam);add(C,4,"xstar",-p.gam);add(C,4,"i",c.LambdaXstarI);add(C,4,"in",-c.LambdaXstarI);add(U,4,"pi",-c.LambdaXstarI);add(C,4,"istar",-c.LambdaXstarIstar);add(C,4,"instar",c.LambdaXstarIstar);add(U,4,"pistar",c.LambdaXstarIstar);add(C,5,"pistar",1);add(U,5,"pistar",-p.beta);add(C,5,"x",-c.kappa*c.Psi1star);add(C,5,"xstar",-c.kappa*c.Psi2star);add(C,6,"istar",1);add(L,6,"istar",-p.rho_istar);add(C,6,"pistar",-(1-p.rho_istar)*p.phi_pistar);add(C,6,"xstar",-(1-p.rho_istar)*p.phi_xstar);add(C,6,"instar",-(1-p.rho_istar)*io);add(C,7,"instar",1);add(C,7,"a",-c.NaturalIstara);add(C,7,"astar",-c.NaturalIstarastar);add(C,8,"y",1);add(C,8,"x",-1);add(C,8,"a",-c.LambdaYa);add(C,8,"astar",-c.LambdaYastar);add(C,9,"ystar",1);add(C,9,"xstar",-1);add(C,9,"a",-c.LambdaYstara);add(C,9,"astar",-c.LambdaYstarastar);add(C,10,"pil1",1);add(L,10,"pi",-1);add(C,11,"a",1);add(L,11,"a",-p.deltaa);add(C,12,"astar",1);add(L,12,"astar",-p.deltaastar);add(C,13,"m",1);add(L,13,"m",-p.deltam);add(C,14,"mstar",1);add(L,14,"mstar",-p.deltamstar);return{L,C,U}}
function mul(A,B){const rows=A.length,inner=B.length,cols=Array.isArray(B[0])?B[0].length:1,out=Array.from({length:rows},()=>Array(cols).fill(0));for(let i=0;i<rows;i++)for(let k=0;k<inner;k++){const a=A[i][k];if(!a)continue;if(cols===1)out[i][0]+=a*B[k];else for(let j=0;j<cols;j++)out[i][j]+=a*B[k][j]}return cols===1?out.map(r=>r[0]):out}const sub=(A,B)=>A.map((r,i)=>r.map((v,j)=>v-B[i][j])),vsub=(a,b)=>a.map((v,i)=>v-b[i]);
function solve(Ain,Bin){const A=Ain.map(r=>r.slice()),isv=!Array.isArray(Bin[0]),B=isv?Bin.map(v=>[v]):Bin.map(r=>r.slice()),n=A.length,m=B[0].length;for(let col=0;col<n;col++){let piv=col,ma=Math.abs(A[col][col]);for(let r=col+1;r<n;r++){const val=Math.abs(A[r][col]);if(val>ma){ma=val;piv=r}}if(ma<1e-12)throw new Error("The model system is singular or too close to singular for this parameterization.");if(piv!==col){[A[col],A[piv]]=[A[piv],A[col]];[B[col],B[piv]]=[B[piv],B[col]]}const d=A[col][col];for(let j=col;j<n;j++)A[col][j]/=d;for(let j=0;j<m;j++)B[col][j]/=d;for(let r=0;r<n;r++){if(r===col)continue;const f=A[r][col];if(!f)continue;for(let j=col;j<n;j++)A[r][j]-=f*A[col][j];for(let j=0;j<m;j++)B[r][j]-=f*B[col][j]}}return isv?B.map(r=>r[0]):B}
function tri(L,C,U,rhs){const H=rhs.length,cp=Array(H),dp=Array(H);cp[0]=solve(C,U);dp[0]=solve(C,rhs[0]);for(let t=1;t<H;t++){const den=sub(C,mul(L,cp[t-1])),adj=vsub(rhs[t],mul(L,dp[t-1]));cp[t]=t===H-1?z():solve(den,U);dp[t]=solve(den,adj)}const x=Array(H);x[H-1]=dp[H-1];for(let t=H-2;t>=0;t--)x[t]=vsub(dp[t],mul(cp[t],x[t+1]));return x}
function shockVector(p,s){const e={eps_a:0,eps_astar:0,eps_m:0,eps_mstar:0},sg=s.sign==="negative"?-1:1,sc=Number(s.scale||1);if(s.type==="eps_a")e.eps_a=sg*sc*p.stda;if(s.type==="eps_astar")e.eps_astar=sg*sc*p.stdastar;if(s.type==="eps_m")e.eps_m=sg*sc*p.stdm;if(s.type==="eps_mstar")e.eps_mstar=sg*sc*p.stdmstar;return e}
function rhs(e,t){const d=Array(N).fill(0);if(t===0){d[2]=e.eps_m;d[6]=e.eps_mstar;d[11]=e.eps_a;d[12]=e.eps_astar;d[13]=e.eps_m;d[14]=e.eps_mstar}return d}
export function solveModel(params,shock,horizon=40){const val=validateParams(params);if(!val.ok)throw new Error(val.messages.join(" "));const c=val.composite,b=blocks(params,c),eps=shockVector(params,shock),sol=tri(b.L,b.C,b.U,Array.from({length:horizon},(_,t)=>rhs(eps,t)));const rows=sol.map((v,t)=>{const r={period:t};VARS.forEach((n,i)=>r[n]=v[i]);r.growth=t===0?r.y:r.y-sol[t-1][IDX.y];r.growthStar=t===0?r.ystar:r.ystar-sol[t-1][IDX.ystar];r.employment=r.y-r.a;r.employmentStar=r.ystar-r.astar;r.totbar=c.ThetaTot*(r.a-r.astar);r.tot=r.totbar+(r.x-r.xstar)/c.D;r.totstar=-r.tot;r.rsbar=c.OmegaRS*r.totbar;r.rs=c.OmegaRS*r.tot;r.rsstar=-r.rs;r.tb=c.omegaTB*c.OmegaTB*r.tot;r.tbstar=-r.tb;return r});return{rows,xistar:val.xistar,composite:c,shockInnovation:eps}}
